---
title: "AD GSEA Script"
author: "Alexander Bergendorf"
date: "2023-09-10"
output: html_document
---

# Library Import
```{r}
library(fgsea)
library(Seurat)
library(mixOmics)
library(tidyverse)
library(orthogene)
library(dittoSeq)
library(openxlsx)
library(EnrichmentBrowser)
library(qusage)
library(ggpubr)
home_dir <- "C:/Users/aberg/OneDrive/Desktop/Brubaker Summer Research 2023"
```


# PCA
## Data Import
```{r}
combined <- readRDS(file = paste0(home_dir, "/AD_mouse_objects_ortholog/mouse_pca_loadings.RData"))
```

## GO
```{r}
# Loads gene set installed from MSigDb
gene_set <- read.gmt(file = paste0(home_dir, "/c5.go.v2023.2.Hs.symbols.gmt"))
# Feature loadings of mouse PCs
mouse_loadings <- combined@reductions$pca@feature.loadings
# Get orthologs of mouse to swap gene names for gene set enrichment analysis
ortholog_mat <- convert_orthologs(gene_df = row.names(mouse_loadings),
                                    input_species = "mouse",
                                    output_species = "human",
                                    non121_strategy = "drop_both_species")
# Ensures same order
mouse_loadings <- mouse_loadings[ortholog_mat$input_gene,]
# Switches to ortholog
row.names(mouse_loadings) <- row.names(ortholog_mat)

# Creates list for fGSEA data frames
fgsea_list <- list()


for(i in 1:50){
  # Pull one pc
  pc_vec <- data.frame(pc = as.numeric(mouse_loadings[,i]))
  # Assign row names from pc_vec to df
  row.names(pc_vec) <- row.names(mouse_loadings)
  # Arrange by pc score
  pc_vec <- pc_vec %>%
  arrange(pc)
  # Convert to numeric
  pc_values <- as.numeric(pc_vec$pc)
  # Assign names to numeric
  names(pc_values) <- row.names(pc_vec)
    
  # Run fGSEA on gene set with pc_value
  fgsea_list[[i]] <- fgsea(pathways = gene_set,
                   stats = pc_values)
}
```

```{r}
# Assigns names to list
names(fgsea_list) <- c("pca_1", "pca_2", "pca_3", "pca_4", "pca_5",
                       "pca_6", "pca_7", "pca_8", "pca_9", "pca_10",
                       "pca_11", "pca_12", "pca_13", "pca_14", "pca_15",
                       "pca_16", "pca_17", "pca_18", "pca_19", "pca_20",
                       "pca_21", "pca_22", "pca_23", "pca_24", "pca_25",
                       "pca_26", "pca_27", "pca_28", "pca_29", "pca_30",
                       "pca_31", "pca_32", "pca_33", "pca_34", "pca_35",
                       "pca_36", "pca_37", "pca_38", "pca_39", "pca_40",
                       "pca_41", "pca_42", "pca_43", "pca_44", "pca_45",
                       "pca_46", "pca_47", "pca_48", "pca_49", "pca_50")


# Arrange fgsea output by adjusted p-value
for(i in names(fgsea_list)){ 
  fgsea_list[[i]] <- arrange(fgsea_list[[i]], padj)

} 

# Save results
write.xlsx(fgsea_list, file = paste0(home_dir, "/fgsea_pca_results_go.xlsx"))
```


## KEGG
```{r}
gene_set <- read.gmt(file = paste0(home_dir, "/c2.cp.kegg.v2023.1.Hs.symbols.gmt"))
mouse_loadings <- combined@reductions$pca@feature.loadings
ortholog_mat <- convert_orthologs(gene_df = row.names(mouse_loadings),
                                    input_species = "mouse",
                                    output_species = "human",
                                    non121_strategy = "drop_both_species")
mouse_loadings <- mouse_loadings[ortholog_mat$input_gene,]
row.names(mouse_loadings) <- row.names(ortholog_mat)

ortholog_mat
fgsea_list <- list()

for(i in 1:50){
  pc_vec <- data.frame(pc = as.numeric(mouse_loadings[,i]))
  row.names(pc_vec) <- row.names(mouse_loadings)
  pc_vec <- pc_vec %>%
  arrange(pc)
  pc_values <- as.numeric(pc_vec$pc)
  names(pc_values) <- row.names(pc_vec)
    

  #fgsea_list[[i]] <- fgsea(pathways = gene_set,
                   #stats = pc_values)
}
```


```{r}
names(fgsea_list) <- c("pca_1", "pca_2", "pca_3", "pca_4", "pca_5",
                       "pca_6", "pca_7", "pca_8", "pca_9", "pca_10",
                       "pca_11", "pca_12", "pca_13", "pca_14", "pca_15",
                       "pca_16", "pca_17", "pca_18", "pca_19", "pca_20",
                       "pca_21", "pca_22", "pca_23", "pca_24", "pca_25",
                       "pca_26", "pca_27", "pca_28", "pca_29", "pca_30",
                       "pca_31", "pca_32", "pca_33", "pca_34", "pca_35",
                       "pca_36", "pca_37", "pca_38", "pca_39", "pca_40",
                       "pca_41", "pca_42", "pca_43", "pca_44", "pca_45",
                       "pca_46", "pca_47", "pca_48", "pca_49", "pca_50")



for(i in 1:50){ 
  fgsea_list[[i]] <- arrange(fgsea_list[[i]], padj)
} 

write.xlsx(fgsea_list, file = paste0(home_dir, "/fgsea_pca_results_kegg.xlsx"))
```


# sPCA
## Data Import
```{r}
combined <- readRDS(file = paste0(home_dir, "/AD_mouse_objects_ortholog/mouse_spca_loadings.RData"))
```

## GO
```{r}
gene_set <- read.gmt(file = paste0(home_dir, "/c5.go.v2023.2.Hs.symbols.gmt"))
mouse_loadings <- combined@reductions$pca@feature.loadings
ortholog_mat <- convert_orthologs(gene_df = row.names(mouse_loadings),
                                    input_species = "mouse",
                                    output_species = "human",
                                    non121_strategy = "drop_both_species")
mouse_loadings <- mouse_loadings[ortholog_mat$input_gene,]
row.names(mouse_loadings) <- row.names(ortholog_mat)

ortholog_mat
fgsea_list <- list()

for(i in 1:50){
  pc_vec <- as.numeric(mouse_loadings[,i])
  pc_vec <- sort(pc_vec, decreasing = TRUE)
  names(pc_vec) <- row.names(mouse_loadings)

  fgsea_list[[i]] <- fgsea(pathways = gene_set,
                   stats = pc_vec)
}
```

```{r}
names(fgsea_list) <- c("spca_1", "spca_2", "spca_3", "spca_4", "spca_5",
                       "spca_6", "spca_7", "spca_8", "spca_9", "spca_10",
                       "spca_11", "spca_12", "spca_13", "spca_14", "spca_15",
                       "spca_16", "spca_17", "spca_18", "spca_19", "spca_20",
                       "spca_21", "spca_22", "spca_23", "spca_24", "spca_25",
                       "spca_26", "spca_27", "spca_28", "spca_29", "spca_30",
                       "spca_31", "spca_32", "spca_33", "spca_34", "spca_35",
                       "spca_36", "spca_37", "spca_38", "spca_39", "spca_40",
                       "spca_41", "spca_42", "spca_43", "spca_44", "spca_45",
                       "spca_46", "spca_47", "spca_48", "spca_49", "spca_50")



for(i in names(fgsea_list)){ 
  fgsea_list[[i]] <- arrange(fgsea_list[[i]], padj)

} 

write.xlsx(fgsea_list, file = paste0(home_dir, "/fgsea_spca_results_go.xlsx"))
```




## KEGG
```{r}
gene_set <- read.gmt(file = paste0(home_dir, "/c2.cp.kegg.v2023.1.Hs.symbols.gmt"))

mouse_loadings <- combined@reductions$spca@feature.loadings
ortholog_mat <- convert_orthologs(gene_df = row.names(mouse_loadings),
                                    input_species = "mouse",
                                    output_species = "human",
                                    non121_strategy = "drop_both_species")
mouse_loadings <- mouse_loadings[ortholog_mat$input_gene,]
row.names(mouse_loadings) <- row.names(ortholog_mat)

fgsea_list <- list()

for(i in 1:50){
  pc_vec <- data.frame(pc = as.numeric(mouse_loadings[,i]))
  row.names(pc_vec) <- row.names(mouse_loadings)
  pc_vec <- pc_vec %>%
  arrange(pc)
  pc_values <- as.numeric(pc_vec$pc)
  names(pc_values) <- row.names(pc_vec)
    

  fgsea_list[[i]] <- fgsea(pathways = gene_set,
                   stats = pc_values)
  
}

```

```{r}
names(fgsea_list) <- c("spca_1", "spca_2", "spca_3", "spca_4", "spca_5",
                       "spca_6", "spca_7", "spca_8", "spca_9", "spca_10",
                       "spca_11", "spca_12", "spca_13", "spca_14", "spca_15",
                       "spca_16", "spca_17", "spca_18", "spca_19", "spca_20",
                       "spca_21", "spca_22", "spca_23", "spca_24", "spca_25",
                       "spca_26", "spca_27", "spca_28", "spca_29", "spca_30",
                       "spca_31", "spca_32", "spca_33", "spca_34", "spca_35",
                       "spca_36", "spca_37", "spca_38", "spca_39", "spca_40",
                       "spca_41", "spca_42", "spca_43", "spca_44", "spca_45",
                       "spca_46", "spca_47", "spca_48", "spca_49", "spca_50")



for(i in names(fgsea_list)){ 
  fgsea_list[[i]] <- arrange(fgsea_list[[i]], padj)

} 

write.xlsx(fgsea_list, file = paste0(home_dir, "/fgsea_spca_results_KEGG.xlsx"))
```


```{r}
sessionInfo()
```

