---
title: "AD Suvorexant Signature"
author: "Alexander Bergendorf"
date: "2023-10-20"
output: html_document
---

# Library Import
```{r}
library(Seurat)
library(mixOmics)
library(h2o)
library(tidyverse)
library(orthogene)
library(dittoSeq)
library(openxlsx)
library(readr)
library(ggcorrplot)
home_dir <- "C:/Users/aberg/OneDrive/Desktop/Brubaker Summer Research 2023"
```

# PCA
```{r}
combined <- readRDS(file = paste0(home_dir, "/AD_mouse_objects_ortholog/mouse_pca_loadings.RData"))
```

```{r}
suvo <- read_tsv(paste0(home_dir, "/AD_human_objects_ortholog/cp_mean_coeff_suvo.tsv"))
#suvo <- read.csv(paste0(home_dir, "/AD_human_objects_ortholog/cp_suvo_filtered.csv"), row.names = 1)
```



```{r}
suvo <- suvo[,-1]
suvo <- data.frame(t(suvo))
colnames(suvo) <- c("Suvorexant_score")
suvo
```

```{r}
pca_loadings <- data.frame(combined@reductions$pca@feature.loadings)
```




```{r}
nrow(suvo)
nrow(pca_loadings)
```

```{r}
mouse_genes <- row.names(pca_loadings)
human_genes <- row.names(suvo)
```


Need to filter to make even
```{r}
adjusted_mouse <- convert_orthologs(gene_df = mouse_genes,
                                    input_species = "mouse",
                                    output_species = "human",
                                    non121_strategy = "drop_both_species")
```

```{r}
adjusted_human <- convert_orthologs(gene_df = human_genes,
                                    input_species = "human",
                                    output_species = "mouse",
                                    non121_strategy = "drop_both_species")
```

```{r}
length(row.names(adjusted_mouse))
adjusted_mouse <- adjusted_mouse %>%
  filter(row.names(adjusted_mouse) %in% adjusted_human$input_gene)
length(row.names(adjusted_mouse))
```

```{r}
length(row.names(adjusted_human))
adjusted_human <- adjusted_human %>%
  filter(row.names(adjusted_human) %in% adjusted_mouse$input_gene)
length(row.names(adjusted_human))
```

```{r}
length(row.names(adjusted_mouse))
adjusted_mouse <- adjusted_mouse %>%
  filter(row.names(adjusted_mouse) %in% adjusted_human$input_gene)
length(row.names(adjusted_mouse))
```


```{r}
suvo <- suvo %>%
  filter(row.names(suvo) %in% adjusted_human$input_gene)
row.names(suvo) <- row.names(adjusted_human)
suvo
```
```{r}
pca_loadings <- pca_loadings %>%
  filter(row.names(pca_loadings) %in% adjusted_mouse$input_gene)
pca_loadings
```


```{r}
suvo <- suvo %>%
  arrange(row.names(suvo))
pca_loadings <- pca_loadings %>%
  arrange(row.names(pca_loadings))
```

```{r}
head(suvo)
head(pca_loadings)
```

```{r}
write.csv(pca_loadings, file = paste0(home_dir, "/drug_orthologs/pca_loadings.csv"), row.names = TRUE)
write.csv(suvo, file = paste0(home_dir, "/drug_orthologs/suvo_orthologs.csv"), row.names = TRUE)
```

```{r}
significant_pcs <- c(1, 2, 3, 6, 9, 10,
                     11, 12, 15, 16, 19,
                     23, 25, 26, 28, 29,
                     31, 33, 38, 39,
                     41, 46, 47, 48, 50)
pca_loadings <- pca_loadings[,significant_pcs]
```


```{r}
suvo_mouse_cor_pca <- cor(pca_loadings, suvo, method = c("spearman"))
```

```{r}
ggcorrplot(suvo_mouse_cor_pca)
```

```{r}
#write.csv(suvo_mouse_cor_pca, file = paste0(home_dir, "/correlations/suvorexant_pca_nofilter.csv"))
write.csv(suvo_mouse_cor_pca, file = paste0(home_dir, "/correlations/suvorexant_pca_filter.csv"))
```


```{r}
max(suvo_mouse_cor_pca)
min(suvo_mouse_cor_pca)
```


# End
```{r}

```

